import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.services.orchestrator import AgentOrchestrator


def assert_true(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def test_agents_generate_from_course_knowledge_base() -> None:
    result = AgentOrchestrator().run(
        session_id="agent_generation_test",
        course_id="data_structures",
        user_message="我是软件工程大二学生，想48小时学习数据结构，为了考试通过，喜欢图解和练习题。",
    )

    assert_true(result["knowledge_context"]["source"] == "course_knowledge_base", "knowledge source should be real course KB")
    assert_true(result["knowledge_context"]["course_id"] == "data_structures", "course id should be preserved")
    assert_true(len(result["diagnosis"]["weak_knowledge_points"]) >= 2, "diagnosis should contain weak points")
    assert_true(len(result["learning_path"]) >= 2, "planner should generate multiple stages")
    assert_true(result["learning_path"][0]["source"] == "agent_generated", "learning path should be generated by agent")
    assert_true(
        all("3-2" not in stage["duration"] and "4-2" not in stage["duration"] for stage in result["learning_path"]),
        "short timeline should not produce inverted day ranges",
    )
    assert_true(all(item["source"] == "agent_generated" for item in result["resources"]), "resources should not be mock")
    assert_true(
        {"lecture", "mindmap", "quiz", "reading", "practice", "multimodal"}.issubset(
            {item["type"] for item in result["resources"]}
        ),
        "resources should cover required resource types",
    )
    assert_true(result["review"]["quality_status"] == "passed", "generated result should pass quality review")
    assert_true(result["review"]["anti_hallucination"]["enabled"], "anti-hallucination review should be enabled")
    assert_true(
        result["review"]["anti_hallucination"]["knowledge_source"] == "course_knowledge_base",
        "review should record course KB as grounding source",
    )


if __name__ == "__main__":
    test_agents_generate_from_course_knowledge_base()
    print("PASS agent_generation_test")
