import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.services.orchestrator import AgentOrchestrator
from app.agents.diagnosis_agent import DiagnosisAgent
from app.config import settings


def assert_true(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def test_agents_generate_from_course_knowledge_base() -> None:
    result = AgentOrchestrator().run(
        session_id="agent_generation_test",
        course_id="data_structures",
        user_message="我是软件工程大二学生，想48小时学习数据结构，为了考试通过，喜欢图解和练习题。",
    )

    assert_true(result["knowledge_context"]["source"] == "course_knowledge_base", "knowledge source should be real course KB")
    assert_true(result["knowledge_context"]["course_id"] == "data_structures", "course id should be preserved")
    expected_profile_keys = [
        "major_background",
        "knowledge_base",
        "learning_goal",
        "cognitive_style",
        "error_patterns",
        "coding_ability",
        "learning_progress",
        "interest_direction",
        "learning_rhythm",
        "self_efficacy",
    ]
    assert_true(list(result["profile"].keys()) == expected_profile_keys, "profile should use stable 10-dimension keys")
    assert_true(
        all(
            all(field in result["profile"][key] for field in ("score", "confidence", "explanation", "evidence", "source"))
            for key in expected_profile_keys
        ),
        "profile dimensions should include structured profile fields",
    )
    assert_true(len(result["diagnosis"]["weak_knowledge_points"]) >= 2, "diagnosis should contain weak points")
    assert_true(
        all(
            field in result["diagnosis"]
            for field in ("weak_topics", "reason", "source", "confidence", "next_actions", "limitations")
        ),
        "diagnosis should expose the structured P0 contract",
    )
    assert_true(len(result["learning_path"]) >= 2, "planner should generate multiple stages")
    assert_true(result["estimatedDays"] == 2, "48 hours should be planned as 2 days")
    assert_true(result["learning_path"][0]["source"] == "agent_generated", "learning path should be generated by agent")
    assert_true(
        all("3-2" not in stage["duration"] and "4-2" not in stage["duration"] for stage in result["learning_path"]),
        "short timeline should not produce inverted day ranges",
    )
    assert_true(
        all(item["source"] in {"llm_generated", "rule_based_fallback"} for item in result["resources"]),
        "resources should distinguish real LLM generation from rule fallback",
    )
    assert_true(
        all(item.get("related_stage_id") and item.get("related_knowledge_points") for item in result["resources"]),
        "resources should be bound to stages and knowledge points",
    )
    assert_true(
        {"lecture", "mindmap", "quiz", "reading", "practice", "multimodal"}.issubset(
            {item["type"] for item in result["resources"]}
        ),
        "resources should cover required resource types",
    )
    assert_true(result["review"]["quality_status"] == "passed", "generated result should pass quality review")
    assert_true(result["review"]["anti_hallucination"]["enabled"], "anti-hallucination review should be enabled")
    assert_true(
        result["review"]["anti_hallucination"]["knowledge_source"] == "course_knowledge_base",
        "review should record course KB as grounding source",
    )


def test_demo_mock_fallback_is_not_product_default() -> None:
    assert_true(settings.enable_mock_fallback is False, "demo_result fallback should be opt-in")


def test_diagnosis_does_not_read_demo_when_knowledge_is_empty() -> None:
    agent = DiagnosisAgent(
        mock_data={
            "diagnosis": {
                "weak_knowledge_points": [
                    {"name": "DEMO_POINT_SHOULD_NOT_APPEAR", "priority": "high"}
                ]
            }
        }
    )
    result = agent.run({"knowledge_context": {"retrieved_points": []}, "profile": {}})
    diagnosis = result["diagnosis"]

    assert_true(diagnosis["weak_knowledge_points"] == [], "empty knowledge should not use demo weak points")
    assert_true(
        "DEMO_POINT_SHOULD_NOT_APPEAR" not in str(diagnosis),
        "demo point must not leak into product diagnosis",
    )
    assert_true(diagnosis["limitations"], "insufficient data should be disclosed")
    assert_true(diagnosis["confidence"] < 0.5, "insufficient-data diagnosis should have low confidence")


def test_diagnosis_uses_profile_path_and_resources() -> None:
    diagnosis = DiagnosisAgent().run(
        {
            "profile": {
                "error_patterns": {"value": "链表不熟", "source": "user_input"},
                "knowledge_base": {"value": "C 语言基础一般"},
            },
            "learning_path": [
                {
                    "stage_id": "stage_linked_list",
                    "title": "链表与线性表",
                    "goal": "掌握链表操作",
                    "tasks": ["实现单链表"],
                }
            ],
            "resources": [
                {
                    "resource_id": "session_res_linked_list",
                    "title": "链表代码案例",
                    "related_stage_id": "stage_linked_list",
                    "related_knowledge_points": ["链表"],
                }
            ],
            "analytics": {"eventCount": 0, "weakTopics": []},
        }
    )["diagnosis"]

    topic = diagnosis["weak_topics"][0]
    assert_true(topic["topic"] == "链表", "profile weakness should drive the diagnosis topic")
    assert_true(topic["recommended_stage_id"] == "stage_linked_list", "topic should bind to the learning path")
    assert_true(
        topic["recommended_resource_ids"] == ["session_res_linked_list"],
        "topic should bind to a matching session resource",
    )
    assert_true(
        any("行为数据" in item for item in diagnosis["limitations"]),
        "diagnosis without learning events must state the evidence limitation",
    )


if __name__ == "__main__":
    test_agents_generate_from_course_knowledge_base()
    test_demo_mock_fallback_is_not_product_default()
    test_diagnosis_does_not_read_demo_when_knowledge_is_empty()
    test_diagnosis_uses_profile_path_and_resources()
    print("PASS agent_generation_test")
